// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Core.SpecFlow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Environment Verification Processor")]
    public partial class EnvironmentVerificationProcessorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EnvironmentVerificationProcessor.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Environment Verification Processor", "In order to process a batch of environment artifacts\r\nAs a service user \r\nI want " +
                    "to be told the status of all the artifacts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When 3 items are passed, check for count")]
        public virtual void When3ItemsArePassedCheckForCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When 3 items are passed, check for count", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a new EnvironmentVerificationProcessor");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "type",
                        "name",
                        "location"});
            table1.AddRow(new string[] {
                        "File",
                        "Template",
                        "D:\\AppShare\\DataSuite\\Templates\\UtilFunctions.xslt"});
            table1.AddRow(new string[] {
                        "Directory",
                        "TemplateDirectory",
                        "D:\\AppShare\\DataSuite\\Templates"});
            table1.AddRow(new string[] {
                        "Invalid",
                        "InvalidName",
                        "Test"});
#line 8
 testRunner.When("I add items for processing", ((string)(null)), table1);
#line 13
 testRunner.Then("the Environment Verification Processor result count should be 3");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When 2 Valid and 1 invalid items are passed, check return value")]
        public virtual void When2ValidAnd1InvalidItemsArePassedCheckReturnValue()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When 2 Valid and 1 invalid items are passed, check return value", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I have a new EnvironmentVerificationProcessor");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "type",
                        "name",
                        "location"});
            table2.AddRow(new string[] {
                        "File",
                        "Template",
                        "D:\\AppShare\\DataSuite\\Templates\\UtilFunctions.xslt"});
            table2.AddRow(new string[] {
                        "Directory",
                        "TemplateDirectory",
                        "D:\\AppShare\\DataSuite\\Templates"});
            table2.AddRow(new string[] {
                        "Invalid",
                        "InvalidName",
                        "Test"});
#line 17
 testRunner.When("I add items for processing", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "canConnect",
                        "message"});
            table3.AddRow(new string[] {
                        "True",
                        "Passed connecting to Templates, file path: D:\\AppShare\\DataSuite\\Templates\\UtilFu" +
                            "nctions.xslt"});
            table3.AddRow(new string[] {
                        "True",
                        "Passed connecting to Templates, path: D:\\AppShare\\DataSuite\\Templates"});
            table3.AddRow(new string[] {
                        "False",
                        "Failed, Could not find a valid verifier for name: InvalidName, location: Test"});
#line 22
 testRunner.Then("the Environment Verification Processor result should be", ((string)(null)), table3);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
