// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Core.SpecFlow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Json Resource Item Processor")]
    public partial class JsonResourceItemProcessorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "JsonResourceItemProcessor.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Json Resource Item Processor", "In order to process a Json string\r\nAs a service user \r\nI want to be provided a li" +
                    "st of all the parsed Resource item lists", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When a valid Json string is passed with 3 items, check count")]
        public virtual void WhenAValidJsonStringIsPassedWith3ItemsCheckCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a valid Json string is passed with 3 items, check count", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a new JsonResourceItemProcessor");
#line 8
 testRunner.When("I add Json objects for processing [{\"ItemType\":\"File\",\"Identifier\":\"File1\",\"Locat" +
                    "ion\":\"FileLocation1\"},{\"ItemType\":\"File\",\"Identifier\":\"File1\",\"Location\":\"FileLo" +
                    "cation1\"},{\"ItemType\":\"File\",\"Identifier\":\"File1\",\"Location\":\"FileLocation1\"}]");
#line 9
 testRunner.Then("the Json result should have a count of 3");
#line 10
 testRunner.Then("the Json result for type File should have a count of 3");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When a valid Json string is passed with 1 File and 2 Directory, check count")]
        public virtual void WhenAValidJsonStringIsPassedWith1FileAnd2DirectoryCheckCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When a valid Json string is passed with 1 File and 2 Directory, check count", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I have a new JsonResourceItemProcessor");
#line 14
 testRunner.When("I add Json objects for processing [{\"ItemType\":\"File\",\"Identifier\":\"File1\",\"Locat" +
                    "ion\":\"FileLocation1\"},{\"ItemType\":\"Directory\",\"Identifier\":\"File1\",\"Location\":\"F" +
                    "ileLocation1\"},{\"ItemType\":\"Directory\",\"Identifier\":\"File1\",\"Location\":\"FileLoca" +
                    "tion1\"}]");
#line 15
 testRunner.Then("the Json result should have a count of 3");
#line 16
 testRunner.Then("the Json result for type File should have a count of 1");
#line 17
 testRunner.Then("the Json result for type Directory should have a count of 2");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
