// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Core.SpecFlow.Verifiers
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("File Verfication")]
    public partial class FileVerficationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FileVerification.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "File Verfication", "In order to verify if a File exists in a system\r\nAs a system user\r\nI want to be t" +
                    "old if the File exists", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For an existing File, check the result message")]
        public virtual void ForAnExistingFileCheckTheResultMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For an existing File, check the result message", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a new FileVerifier");
#line 8
 testRunner.When("I add a File path, identifier: Templates, path: D:\\AppShare\\DataSuite\\Templates\\U" +
                    "tilFunctions.xslt");
#line 9
 testRunner.Then("the File verification result message should be Success connecting to Templates, K" +
                    "ey: FilePath, Value: D:\\AppShare\\DataSuite\\Templates\\UtilFunctions.xslt");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For an existing File, check the result type")]
        public virtual void ForAnExistingFileCheckTheResultType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For an existing File, check the result type", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I have a new FileVerifier");
#line 13
 testRunner.When("I add a File path, identifier: Templates, path: D:\\AppShare\\DataSuite\\Templates\\U" +
                    "tilFunctions.xslt");
#line 14
 testRunner.Then("the File verification status should be Success");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For an existing File, check the result count")]
        public virtual void ForAnExistingFileCheckTheResultCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For an existing File, check the result count", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I have a new FileVerifier");
#line 18
 testRunner.When("I add a File path, identifier: Templates, path: D:\\AppShare\\DataSuite\\Templates\\U" +
                    "tilFunctions.xslt");
#line 19
 testRunner.Then("the File verification count should be 1");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For a non existent File, check the result message")]
        public virtual void ForANonExistentFileCheckTheResultMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For a non existent File, check the result message", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I have a new FileVerifier");
#line 23
 testRunner.When("I add a File path, identifier: Invalid, path: D:\\AppShare\\DataSuite\\Invalid\\UtilF" +
                    "unctions.xslt");
#line 24
 testRunner.Then("the File verification result message should be Failure connecting to Invalid, Err" +
                    "or Message: File not found, Key: FilePath, Value: D:\\AppShare\\DataSuite\\Invalid\\" +
                    "UtilFunctions.xslt");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For a non existent File, check the result type")]
        public virtual void ForANonExistentFileCheckTheResultType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For a non existent File, check the result type", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I have a new FileVerifier");
#line 28
 testRunner.When("I add a File path, identifier: Invalid, path: D:\\AppShare\\DataSuite\\Invalid\\UtilF" +
                    "unctions.xslt");
#line 29
 testRunner.Then("the File verification status should be Failure");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("For a non existent File, check the result count")]
        public virtual void ForANonExistentFileCheckTheResultCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("For a non existent File, check the result count", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I have a new FileVerifier");
#line 33
 testRunner.When("I add a File path, identifier: Invalid, path: D:\\AppShare\\DataSuite\\Invalid\\UtilF" +
                    "unctions.xslt");
#line 34
 testRunner.Then("the File verification count should be 1");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 File are added, check the result count")]
        public virtual void _3FileAreAddedCheckTheResultCount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 File are added, check the result count", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("I have a new FileVerifier");
#line 38
 testRunner.When("I add a File path, identifier: Templates, path: D:\\AppShare\\DataSuite\\Templates\\U" +
                    "tilFunctions.xslt");
#line 39
 testRunner.When("I add a File path, identifier: Invalid, path: D:\\AppShare\\DataSuite\\Invalid\\UtilF" +
                    "unctions.xslt");
#line 40
 testRunner.When("I add a File path, identifier: Invalid, path: D:\\AppShare\\DataSuite\\Invalid\\UtilF" +
                    "unctions.xslt");
#line 41
 testRunner.Then("the File verification count should be 3");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
